version: 2

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9].[0-9].[0-9]+.*/

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: Install platform tools 
          command: sudo apt-get install bzr time -y
      - run:
          name: Install Go tools
          command: make install-tools
      - run:
          name: Verify
          command: make ci
      - run:
          name: Build collector 
          command: make otelcontribcol
      - store_artifacts:
          path: testbed/tests/results
      - store_test_results:
          path: testbed/tests/results/junit
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: circleci/golang:1.13
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            make docker-otelcontribcol
            docker tag otelcontribcol:latest omnition/opentelemetry-collector:${CIRCLE_TAG:1}
            docker tag otelcontribcol:latest omnition/opentelemetry-collector:latest
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Push image
          command: |
            docker push omnition/opentelemetry-collector:${CIRCLE_TAG:1}
            docker push omnition/opentelemetry-collector:latest
