version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    environment:
      - ZPAGES_ENDPOINT=5567
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./label.txt:/etc/label.txt
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "5567:5567"   # zpages extension
    depends_on:
      - jaeger-all-in-one
      # - zipkin-all-in-one

  # Agent
  otel-agent:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
      - ./agent-zpages-endpoint.txt:/etc/agent-zpages-endpoint.txt
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14250"       # Jaeger grpc receiver
      - "14268"       # Jaeger http thrift receiver
      - "55678"       # OpenCensus receiver
      - "4317"        # OTLP gRPC receiver
      - "9411"        # Zipkin receiver
      - "1777:1777"   # pprof extension
      - "5569:5569"   # zpages extension
      - "13133"       # health_check
    depends_on:
      - otel-collector

  # Synthetic load generators
  jaeger-emitter:
    image: omnition/synthetic-load-generator:1.0.25
    environment:
      - JAEGER_COLLECTOR_URL=http://otel-agent:14268
    depends_on:
      - otel-agent

  zipkin-emitter:
    image: omnition/synthetic-load-generator:1.0.25
    environment:
      - ZIPKINV2_JSON_URL=http://otel-agent:9411/api/v2/spans
    depends_on:
      - otel-agent

  metrics-load-generator:
    build:
      dockerfile: C:\Users\pjanotti\go\src\github.com\open-telemetry\opentelemetry-collector\examples\demo/app/Dockerfile
      context: ./app
    environment:
      - OTEL_AGENT_ENDPOINT=otel-agent:4317
    depends_on:
      - otel-agent

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
